// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAudcLzW7SWPOYvCDIiuMcDipRFo_1Gtqw',
    appId: '1:312994959798:web:b35a18249905d19ad6f117',
    messagingSenderId: '312994959798',
    projectId: 'gothomhack-a75a2',
    authDomain: 'gothomhack-a75a2.firebaseapp.com',
    storageBucket: 'gothomhack-a75a2.appspot.com',
    measurementId: 'G-FD2SK56RR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEdO61-uRIBSwRvxeUUm3ssEd2Hb36MbU',
    appId: '1:312994959798:android:b4536d19c9d07e48d6f117',
    messagingSenderId: '312994959798',
    projectId: 'gothomhack-a75a2',
    storageBucket: 'gothomhack-a75a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMXoKAe4gdV2-z0h7nXXP4DeiesSapdI8',
    appId: '1:312994959798:ios:142b9f7352bf5fcbd6f117',
    messagingSenderId: '312994959798',
    projectId: 'gothomhack-a75a2',
    storageBucket: 'gothomhack-a75a2.appspot.com',
    iosBundleId: 'com.example.gothomhack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMXoKAe4gdV2-z0h7nXXP4DeiesSapdI8',
    appId: '1:312994959798:ios:3571315c03a6c62fd6f117',
    messagingSenderId: '312994959798',
    projectId: 'gothomhack-a75a2',
    storageBucket: 'gothomhack-a75a2.appspot.com',
    iosBundleId: 'com.example.gothomhack.RunnerTests',
  );
}
